version: "3"

services:
  gingonic:
      image: iflavoursbv/go-gin-alpine
      command: go run main.go
      restart: on-failure
      working_dir: /app
      volumes:
        - .:/app
      ports:
        - "3001:3001"
  mysql:
      image: endial/mysql-alpine
      volumes:
        - "miau:/var/lib/mysql"
      networks:
        - mysql_net

volumes:
  miau:
networks:
  mysql_net: