version: "3"
services:
  go:
    build: backend/go
    image: golang:alpine
    working_dir: /go/src/github.com/reji/backend/go
    # restart: always
    command: fresh
    volumes:
      - .:/go/src/github.com/reji
      - /go/src/github.com/reji/backend/go/vendor
    ports:
      - "3001:3001"
    networks:
      - mysql_net
      - redis
    environment:
    - "DB_PORT=3306"
    - "DB_HOST=mysql"
    - "DB_ROOT=root"
    - "DB_NAME=reji"
    - "DB_PASS=test"
    - "REDIS_URL= redis:6379"
    
    depends_on:
      - mysql

  mysql:
    image: woahbase/alpine-mysql
    restart: on-failure
    volumes:
      - "miau:/var/lib/mysql"
    networks:
      - mysql_net
    environment:
      MYSQL_USER_DB: reji
      MYSQL_ROOT_PWD: test

  angular:
    build: frontend
    image: alpine:latest
    volumes: 
      - ./frontend:/app
    working_dir: /app
    command: sh -c "./node_modules/.bin/ng serve --host 0.0.0.0"
    ports: 
      - "4200:4200"
    networks:
      - mysql_net
    environment: 
      - "REDIS_URL= redis:6379"

  redis:
    image: redis:alpine
    restart: on-failure
    ports: 
      - "6379:6379"
    volumes:
      - "redis:/redis_data"
    networks: 
      - redis


volumes:
  miau:
  redis:

networks:
  mysql_net:
  redis:
