version: "3"
services:
  go:
    build: .
    image: golang:alpine
    restart: on-failure
    volumes:
      - .:/go/src/github.com/reji/backend
      - /go/src/github.com/reji/backend/vendor
    ports:
      - "3001:3001"
    networks:
          - mysql_net
    environment:
    - "DB_PORT=3306"
    - "DB_HOST=mysql"
    - "DB_ROOT=root"
    - "DB_NAME=reji"
    - "DB_PASS=test"

  mysql:
    image: endial/mysql-alpine
    restart: on-failure
    volumes:
      - "miau:/var/lib/mysql"
    networks:
      - mysql_net
    environment:
      MYSQL_DATABASE: reji
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: test
frontend:
  build: frontend
  image: alpine:latest
  volumes: 
    - ./frontend:/app
  working_dir: /app
  command: sh -c "npm i && ng serve --host 0.0.0.0"
  ports: 
    - "4200:4200"
  networks:
    - mysql_net

volumes:
  miau:
networks:
  mysql_net:

  # frontend:
