version: '3'
services:
  backend:
    build: .
    image: golang-gin:latest
    volumes:
      - .:/go/src/github.com/wangzitian0/golang-gin-starter-kit
      - /go/src/github.com/wangzitian0/golang-gin-starter-kit/vendor
    ports:
      - "8080:8080"
    networks:
      - mysql_net
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "DB_ROOT=root"
      - "DB_NAME=regi"
      - "DB_PASS=test"
  mysql:
      image: endial/mysql-alpine
      restart: on-failure
      volumes:
        - "miau:/var/lib/mysql"
      networks:
        - mysql_net
      environment:
        MYSQL_DATABASE: regi
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_PASSWORD: test

volumes:
  miau:
networks:
  mysql_net: