CREATE DATABASE IF NOT EXISTS reji;
use reji;
CREATE TABLE IF NOT EXISTS names (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);
INSERT INTO names VALUES (5,"rauojeda11231231");